
# > `bundle exec jekyll serve`


title: Sean.Kerw.in
description: >-
  Writes code.  Former SpaceX, former Bird.  Loves his wife, his cats, and paperclips.
baseurl: ""
url: "https://sean.kerw.in/"
permalink: /archives/:year/:month/:title:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

social:
  stackoverflow: "89209"
  linkedin: seankerwin
  github: skirwan
  twitter: skirwan

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - blogimport/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/